project_name: glimesh-obs-service-patcher
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives: 
  - format_overrides:
      - goos: windows
        format: zip
